apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: swiggy
  template:
    metadata:
      labels:
        app: swiggy
    spec:
      containers:
        - name: cont1
          image: viswanathkasi/superapp
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: cm1
          env:
            - name: secret_code
              valueFrom:
                secretKeyRef:
                  name: sec1
                  key: code
          resources:
            requests:
              cpu: "50m"
              memory: "10Mi"
            limits:
              cpu: "100m"
              memory: "15Mi"         
      imagePullSecrets:
        - name: dockerhub-credentials
